namespace TravelAgency.Shared.Internationalization
{
    public class SpokenLanguagesByIsoCountry
    {
#pragma warning disable CA2211
        public static Dictionary<string, string[]> CountrySpokenLanguageCombinations = new()
        {
            { "AF", new[] { "fa", "ps" } },
            { "AL", new[] { "sq" } },
            { "DZ", new[] { "ar" } },
            { "AD", new[] { "ca" } },
            { "AO", new[] { "pt" } },
            { "AG", new[] { "en" } },
            { "AR", new[] { "es" } },
            { "AM", new[] { "hy" } },
            { "AU", new[] { "en" } },
            { "AT", new[] { "de" } },
            { "AZ", new[] { "az" } },
            { "BS", new[] { "en" } },
            { "BH", new[] { "ar" } },
            { "BD", new[] { "bn" } },
            { "BB", new[] { "en" } },
            { "BY", new[] { "be", "ru" } },
            { "BE", new[] { "nl", "fr", "de" } },
            { "BZ", new[] { "en" } },
            { "BJ", new[] { "fr" } },
            { "BT", new[] { "dz" } },
            { "BO", new[] { "es", "ay", "qu" } },
            { "BA", new[] { "bs", "hr", "sr" } },
            { "BW", new[] { "en", "tn" } },
            { "BR", new[] { "pt" } },
            { "BN", new[] { "ms" } },
            { "BG", new[] { "bg" } },
            { "BF", new[] { "fr" } },
            { "BI", new[] { "fr" } },
            { "CV", new[] { "pt" } },
            { "KH", new[] { "km" } },
            { "CM", new[] { "fr", "en" } },
            { "CA", new[] { "en", "fr" } },
            { "CF", new[] { "fr", "sg" } },
            { "TD", new[] { "fr", "ar" } },
            { "CL", new[] { "es" } },
            { "CN", new[] { "zh" } },
            { "CO", new[] { "es" } },
            { "KM", new[] { "ar", "fr" } },
            { "CG", new[] { "fr" } },
            { "CD", new[] { "fr" } },
            { "CR", new[] { "es" } },
            { "CI", new[] { "fr" } },
            { "HR", new[] { "hr" } },
            { "CU", new[] { "es" } },
            { "CY", new[] { "el", "tr" } },
            { "CZ", new[] { "cs" } },
            { "DK", new[] { "da" } },
            { "DJ", new[] { "fr", "ar" } },
            { "DM", new[] { "en" } },
            { "DO", new[] { "es" } },
            { "EC", new[] { "es" } },
            { "EG", new[] { "ar" } },
            { "SV", new[] { "es" } },
            { "GQ", new[] { "es", "fr", "pt" } },
            { "ER", new[] { "ti", "ar", "en" } },
            { "EE", new[] { "et" } },
            { "ET", new[] { "am" } },
            { "FJ", new[] { "en" } },
            { "FI", new[] { "fi", "sv" } },
            { "FR", new[] { "fr" } },
            { "GA", new[] { "fr" } },
            { "GM", new[] { "en" } },
            { "GE", new[] { "ka" } },
            { "DE", new[] { "de" } },
            { "GH", new[] { "en" } },
            { "GR", new[] { "el" } },
            { "GD", new[] { "en" } },
            { "GT", new[] { "es" } },
            { "GN", new[] { "fr" } },
            { "GW", new[] { "pt" } },
            { "GY", new[] { "en" } },
            { "HT", new[] { "fr", "ht" } },
            { "HN", new[] { "es" } },
            { "HU", new[] { "hu" } },
            { "IS", new[] { "is" } },
            { "IN", new[] { "hi", "en" } },
            { "ID", new[] { "id" } },
            { "IR", new[] { "fa" } },
            { "IQ", new[] { "ar", "ku" } },
            { "IE", new[] { "en", "ga" } },
            { "IL", new[] { "he", "ar" } },
            { "IT", new[] { "it" } },
            { "JM", new[] { "en" } },
            { "JP", new[] { "ja" } },
            { "JO", new[] { "ar" } },
            { "KZ", new[] { "kk", "ru" } },
            { "KE", new[] { "en", "sw" } },
            { "KI", new[] { "en" } },
            { "KP", new[] { "ko" } },
            { "KR", new[] { "ko" } },
            { "KW", new[] { "ar" } },
            { "KG", new[] { "ky", "ru" } },
            { "LA", new[] { "lo" } },
            { "LV", new[] { "lv" } },
            { "LB", new[] { "ar", "fr" } },
            { "LS", new[] { "en", "st" } },
            { "LR", new[] { "en" } },
            { "LY", new[] { "ar" } },
            { "LI", new[] { "de" } },
            { "LT", new[] { "lt" } },
            { "LU", new[] { "lb", "de", "fr" } },
            { "MK", new[] { "mk" } },
            { "MG", new[] { "fr", "mg" } },
            { "MW", new[] { "en", "ny" } },
            { "MY", new[] { "ms" } },
            { "MV", new[] { "dv" } },
            { "ML", new[] { "fr" } },
            { "MT", new[] { "mt", "en" } },
            { "MH", new[] { "en", "mh" } },
            { "MR", new[] { "ar", "fr" } },
            { "MU", new[] { "en" } },
            { "MX", new[] { "es" } },
            { "FM", new[] { "en" } },
            { "MD", new[] { "ro" } },
            { "MC", new[] { "fr" } },
            { "MN", new[] { "mn" } },
            { "ME", new[] { "sr", "bs", "sq", "hr" } },
            { "MA", new[] { "ar" } },
            { "MZ", new[] { "pt" } },
            { "MM", new[] { "my" } },
            { "NA", new[] { "en", "af", "de", "hz", "na" } },
            { "NR", new[] { "en", "na" } },
            { "NP", new[] { "ne" } },
            { "NL", new[] { "nl" } },
            { "NZ", new[] { "en", "mi" } },
            { "NI", new[] { "es" } },
            { "NE", new[] { "fr" } },
            { "NG", new[] { "en" } },
            { "NO", new[] { "no", "nb", "nn" } },
            { "OM", new[] { "ar" } },
            { "PK", new[] { "ur", "en" } },
            { "PW", new[] { "en", "pau" } },
            { "PA", new[] { "es" } },
            { "PG", new[] { "en", "tpi", "ho" } },
            { "PY", new[] { "es", "gn" } },
            { "PE", new[] { "es" } },
            { "PH", new[] { "tl", "en" } },
            { "PL", new[] { "pl" } },
            { "PT", new[] { "pt" } },
            { "QA", new[] { "ar" } },
            { "RO", new[] { "ro" } },
            { "RU", new[] { "ru" } },
            { "RW", new[] { "rw", "fr", "en" } },
            { "KN", new[] { "en" } },
            { "LC", new[] { "en" } },
            { "VC", new[] { "en" } },
            { "WS", new[] { "sm", "en" } },
            { "SM", new[] { "it" } },
            { "ST", new[] { "pt" } },
            { "SA", new[] { "ar" } },
            { "SN", new[] { "fr" } },
            { "RS", new[] { "sr" } },
            { "SC", new[] { "fr", "en" } },
            { "SL", new[] { "en" } },
            { "SG", new[] { "en", "ms", "ta", "zh" } },
            { "SK", new[] { "sk" } },
            { "SI", new[] { "sl" } },
            { "SB", new[] { "en" } },
            { "SO", new[] { "so", "ar" } },
            { "ZA", new[] { "af", "en", "nr", "st", "ss", "tn", "ts", "ve", "xh", "zu" } },
            { "ES", new[] { "es" } },
            { "LK", new[] { "si", "ta" } },
            { "SD", new[] { "ar", "en" } },
            { "SR", new[] { "nl" } },
            { "SZ", new[] { "en", "ss" } },
            { "SE", new[] { "sv" } },
            { "CH", new[] { "de", "fr", "it", "rm" } },
            { "SY", new[] { "ar" } },
            { "TJ", new[] { "tg", "ru" } },
            { "TZ", new[] { "sw", "en" } },
            { "TH", new[] { "th" } },
            { "TL", new[] { "pt" } },
            { "TG", new[] { "fr" } },
            { "TO", new[] { "en", "to" } },
            { "TT", new[] { "en" } },
            { "TN", new[] { "ar" } },
            { "TR", new[] { "tr" } },
            { "TM", new[] { "tk", "ru" } },
            { "TV", new[] { "en" } },
            { "UG", new[] { "en", "sw" } },
            { "UA", new[] { "uk" } },
            { "AE", new[] { "ar" } },
            { "GB", new[] { "en" } },
            { "US", new[] { "en" } },
            { "UY", new[] { "es" } },
            { "UZ", new[] { "uz", "ru" } },
            { "VU", new[] { "bi", "en", "fr" } },
            { "VA", new[] { "la", "it" } },
            { "VE", new[] { "es" } },
            { "VN", new[] { "vi" } },
            { "YE", new[] { "ar" } },
            { "ZM", new[] { "en" } },
            { "ZW", new[] { "en", "sn", "nd" } },
        };
#pragma warning restore CA2211
    }
}